version: '3'

services:
  frontend:
    build:
      context: ./devsecops-front
      dockerfile: Dockerfile
    ports:
      - 18000:80

  backend:
    build:
      context: ./devsecops-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=bdangularproject

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=bdangularproject
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
